### ISSUE TITLE
#bin and #uri violate edn and Clojure specs for tags

### ISSUE THREAD

**Issue by steven-collins-omega** [greglook/puget#16]
This probably sounds really nitpicky, but it was actually causing some confusion on our dev team; several of our devs thought that #bin and #uri were just standard Clojure, not realizing they came from puget.

The [edn spec](https://github.com/edn-format/edn#rules-for-tags) says:

> ### rules for tags
>
> Tag symbols without a prefix are reserved by **edn** for built-ins defined using the tag system. 
>
> User tags _**must**_ contain a prefix component, which must be owned by the user (e.g. trademark or domain) or known unique in the communication context.

The [Clojure reference documentation](http://clojure.org/reader#The Reader--Tagged Literals) seems to back this up:

> Reader tags without namespace qualifiers are reserved for Clojure.

Granted, no one else seems to take this very seriously either. spyscope, datomic, and flatland.ordered use "spy", "db" (mostly), and "ordered" respectively; to say that these are "known unique" seems questionable to me at best. But for the most part (with one exception on datomic's part), they at least **have** a prefix which gives some clue as to where it came from and that it's not standard Clojure.

**Comment by greglook** [comment]
Nitpicky perhaps, but I fully admit I'm in the wrong here. :) Puget was originally part of [Vault](/greglook/vault), which needed the `#bin` and `#uri` tags. I also think they should be part of the core EDN built-ins, but until they are these should indeed be namespaced.

If you submit a PR to change these to `#puget/bin` and `#puget/uri` I'll accept it; otherwise I'll get around to it in the next week or so. Sorry for the confusion!
